title: TeC group @ UU
logo: /assets/img/TEC_logo.png
description: Atomistic simulation of electrochemical systems with physics and ML
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
  - jekyll-seo-tag
