title: TeC group @ UU
logo: /assets/img/TEC_logo_v3.png
description: Modeling electrochemical systems with atomistic simulation and ML
google_analytics:
theme: jekyll-theme-minimal
github:
  is_user_page: false
  is_project_page: false
plugins:
  - jemoji
  - jekyll-seo-tag
